# Generated by Django 5.0.3 on 2024-04-01 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whisper_app', '0004_alter_post_image_alter_post_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower', models.CharField(max_length=50)),
                ('following', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='whisperuser',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
