# Generated by Django 5.0.3 on 2024-04-03 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whisper_app', '0006_post_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0)),
            ],
        ),
    ]
