# Generated by Django 5.0.3 on 2024-04-04 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whisper_app', '0007_offset'),
    ]

    operations = [
        migrations.AddField(
            model_name='whisperuser',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
