# Generated by Django 5.0.3 on 2024-04-11 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whisper_app', '0011_alter_follow_id_alter_notification_id_alter_post_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Username',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('image', models.URLField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
