# Generated by Django 5.0.3 on 2024-04-25 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whisper_app', '0012_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whisperuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='./profile/'),
        ),
    ]
