# Generated by Django 5.0.3 on 2024-04-27 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whisper_app', '0013_alter_whisperuser_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='username',
            name='image',
        ),
    ]
