# Generated by Django 5.0.3 on 2024-04-27 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whisper_app', '0014_remove_username_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='username',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='./uknownuser/'),
        ),
    ]
