# Generated by Django 5.0.3 on 2024-05-14 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whisper_app', '0015_username_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='category',
            field=models.CharField(default='general', max_length=50),
        ),
    ]
