# Generated by Django 5.0.3 on 2024-05-16 09:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whisper_app', '0017_alter_notification_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='time',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='whisperuser',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
