# Generated by Django 5.0.3 on 2024-05-16 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whisper_app', '0018_rename_time_post_created_at_whisperuser_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='whisperuser',
            options={'ordering': ['order_index']},
        ),
        migrations.AddField(
            model_name='whisperuser',
            name='order_index',
            field=models.IntegerField(default=0),
        ),
    ]
