# Generated by Django 5.0.3 on 2024-05-16 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whisper_app', '0019_alter_whisperuser_options_whisperuser_order_index'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='whisperuser',
            options={},
        ),
        migrations.RemoveField(
            model_name='whisperuser',
            name='order_index',
        ),
    ]
